name: hackerton_gdg
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.5
  pinput: ^5.0.0
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.17
  equatable: ^2.0.7
  intl: ^0.20.1
  fluttertoast: ^8.2.10
  flutter_dotenv: ^5.2.1
  bloc: ^8.1.4
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

    - assets/new/background/
    - assets/new/character/
    - assets/new/emoji/
    - assets/new/icons/
    - assets/new/onboarding/
    - assets/new/symple_icons/
    - assets/new/article/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100