import 'package:flutter/material.dart';

class CustomColorScheme {
  Color primaryNormal;
  Color primaryStrong;
  Color primaryHeavy;
  Color labelNormal;
  Color labelStrong;
  Color labelNeutral;
  Color labelAlternative;
  Color labelAssistive;
  Color labelDisable;
  Color backgroundNormalNormal;
  Color backgroundNormalAlternative;
  Color backgroundElevatedNormal;
  Color backgroundElevatedAlternative;
  Color interactionInactive;
  Color interactionDisable;
  Color lineNormal;
  Color lineNeutral;
  Color lineAlternative;
  Color statusPositive;
  Color statusCautionary;
  Color statusDestructive;
  Color accentRedorange;
  Color accentLime;
  Color accentCyan;
  Color accentLightblue;
  Color accentBlue;
  Color accentPink;
  Color accentViolet;
  Color inversePrimary;
  Color inverseBackground;
  Color inverseLabel;
  Color staticWhite;
  Color staticBlack;
  Color fillNormal;
  Color fillStrong;
  Color fillAlternative;

  CustomColorScheme({
    required this.primaryNormal,
    required this.primaryStrong,
    required this.primaryHeavy,
    required this.labelNormal,
    required this.labelStrong,
    required this.labelNeutral,
    required this.labelAlternative,
    required this.labelAssistive,
    required this.labelDisable,
    required this.backgroundNormalNormal,
    required this.backgroundNormalAlternative,
    required this.backgroundElevatedNormal,
    required this.backgroundElevatedAlternative,
    required this.interactionInactive,
    required this.interactionDisable,
    required this.lineNormal,
    required this.lineNeutral,
    required this.lineAlternative,
    required this.statusPositive,
    required this.statusCautionary,
    required this.statusDestructive,
    required this.accentRedorange,
    required this.accentLime,
    required this.accentCyan,
    required this.accentLightblue,
    required this.accentBlue,
    required this.accentPink,
    required this.accentViolet,
    required this.inversePrimary,
    required this.inverseBackground,
    required this.inverseLabel,
    required this.staticWhite,
    required this.staticBlack,
    required this.fillNormal,
    required this.fillStrong,
    required this.fillAlternative,
  });
}
